### ISSUE TITLE
Play in Background when I change activity

### ISSUE THREAD

**Issue by hishamag** [google/flutter.plugins#102]
when I change my player activity to another ,the player still playing in background but the object is destroyed , how to deal with that and let the player alive even if changed activity to another ???

**Comment by monkeyswarm** [comment]
Do you mean that
* You do _not_ have background audio set up, as per the README
* You have audio playing, background the app, and want the audio to stop immediately?

**Comment by hishamag** [comment]
hello , thanks for the response. 

for the first point, I have background audio set up. I respect all the required steps .
for the second point, I do not want to stop the audio. I want the audio still playing if I Navigate to another activity and if I return to the player. The slider and the _backgroundAudioPositionSeconds,_backgroundAudioDurationSeconds and the current played sound should resumed . how I should do that ? 

thanks

**Comment by monkeyswarm** [comment]
I believe this functionality is how the example app currently works. This is tested on Android 11, Pixel 3a. 

Hit the play button on card #4, to start background audio.

When I add 

print(positionSeconds);

on the playback callback on line 82, I see it continue to fire even while the app is backgrounded. This shows that the dart portion of the app remains alive, and continues to receive playback position callbacks.

Do you see this same behavior on your device?

**Comment by hishamag** [comment]
Hello, thanks for the response.
yes, you are right , but my issue is when I have multiple activities , Example : we had 3 activities the menu , the player activity and the news activity , so if I started the player and then I navigate to the first activity or the third the player is in background but the play ,pause button on notification bar does not work and also if I returned to the player activity all the informations is destroyed like _backgroundAudio ,position and duration etc ....

**Comment by monkeyswarm** [comment]
If I am reading this correctly, you have a Java-based app, with one or more Activities using Flutter on a per-Activity basis. The Dart/Flutter VM gets destroyed when a particular Activity is destroyed. Is that right?

That's different than most pure Flutter (single-Activity) app uses cases, which have the Dart/Flutter VM running for the full lifecycle of the app. 

So what you want, for a new Dart/Flutter VM in a newly-started Activity to inspect the service and re-attach audio players to existing native audio players (in the Android code), is not supported. 

It's up to you how to proceed. You could attempt to add that change yourself, where you
* Notify the audio service when an activity (and its running audiofileplayers) is going away.
* On recreating the Activity, query the audio service to return newly recreated audiofileplayers from the existing native audio players

However, I'd recommend looking at the plugin's native Android code, and implement your functionality in native Java. The multiple-activities-interacting-with-a-service model of Android does not map well onto Flutter patterns. I don't know of a way to run and control a service in Flutter, without it remaining attached to the Activity which launched it.

I'll leave this issue open in case anyone else has a suggestion for best practices here.

**Comment by monkeyswarm** [comment]
If I am reading this correctly, you have a Java-based app, with one or more Activities using Flutter on a per-Activity. The Dart/Flutter VM gets destroyed when a particular Activity is destroyed. Is that right?

That's different than most pure Flutter (single-Activity) app uses cases, which have the Dart/Flutter VM running for the full lifecycle of the app. 

So what you want, for a new Dart/Flutter VM in a newly-started Activity to inspect the service and re-attach audio players to existing native audio players (in the Android code), is not supported. 

It's up to you how to proceed. You could attempt to add that change yourself, where you
* Notify the audio service when an activity (and its running audiofileplayers) is going away.
* On recreating the Activity, query the audio service to return newly recreated audiofileplayers from the existing native audio players

However, I'd recommend looking at the plugin's native Android code, and implement your functionality in native Java. The multiple-activities-interacting-with-a-service model of Android does not map well onto Flutter patterns. I don't know of a way to run and control a service in Flutter, without it remaining attached to the Activity which launched it.

I'll leave this issue open in case anyone else has a suggestion for best practices here.

**Comment by hishamag** [comment]
Thanks for the response,
yes that's the point.
So, I will try a method and I will get back to you soon.

**Comment by hishamag** [comment]
Hi, I have tried a method and the play now works perfectly but I have another issue it's about if I want to log out the player doesn't want to dispose, how I can deal with that please.
I used this two instructions in my dispose method but the player still working in background.
AudioSystem.instance.removeMediaEventListener(_mediaEventListener);
_backgroundAudio.dispose();

**Comment by monkeyswarm** [comment]
When you call dispose() on a playing Audiofileplayer, it disposes the Dart object, but audio will continue to play at the native level until the end of the file. 

You want to 
1) as mentioned in the comments, call audioplayer.pause (before you call dispose()). This will dispose the underlying native players immediately, instead of allowing it to continue playing after the dart object is disposed.
2) call AudioSystem.stopBackgroundDisplay to clear all the system notifications/etc
