### ISSUE TITLE
[audiofileplayer] Please support null safety

### ISSUE THREAD

**Issue by mr-mmmmore** [google/flutter.plugins#103]
Are there plans to support null safety soon?

All the packages that I use in my app (28) have migrated or are going to be migrated soon, so this is the last package that would prevent the app to run with sound null safety.

**Comment by arodriguezgb** [comment]
+1

**Comment by monkeyswarm** [comment]
Sure, I'll take a look

**Comment by monkeyswarm** [comment]
audiofileplayer 2.0.0 was just committed and published, which uses null safety. Please give it a thorough test, since this can introduce new bugs. Thanks!

**Comment by mr-mmmmore** [comment]
Like described in #120 I see `NullPointerExceptions` occurences on Google Play. It may be related to this update.
