### ISSUE TITLE
Background buttons are disable on IOS

### ISSUE THREAD

**Issue by felixferr** [google/flutter.plugins#110]
version : audiofileplayers 2.0.0
test on platform : ios

Hi, i have an error with null safety on line 225 from the audio_system.dart file "Unhandled Exception: type 'List<String?>' is not a subtype of type 'List<String>' in type cast". So when i make change on this file to List<String?> the background buttons appears but they are not functional.
Can i have help please ? Thx

**Comment by monkeyswarm** [comment]
Is this with the example app, or your own custom code? What version of iOS?

**Comment by felixferr** [comment]
Hi, it's my custom code, on ios 14.2

**Comment by monkeyswarm** [comment]
Is this a compile-time error or runtime error? I am not able to reproduce this when I run the example app. Does the example app work as expected for you? 

Are you sure you are calling setSupportedMediaActions with a "Set\<MediaActionType>" (Not a "Set<MediaActionType?>" nor "Set\<MediaActionType>?"). Check the runtime type of your [actions] parameter.

**Comment by felixferr** [comment]
It's a runtime error. Your example not use null safety...  And I watched the part where I declared MediaActionType and i use "Set<MediaActionType> without "?"

**Comment by monkeyswarm** [comment]
I've updated my example to use null safety and have reproduced the problem.

**Comment by monkeyswarm** [comment]
Ok a fix is pushed to github and also to pub.dev as version 2.0.1. Please try it and let me know of any issues.
