### ISSUE TITLE
Audio not triggered when app is backgrounded / screen off

### ISSUE THREAD

**Issue by asorokin** [google/flutter.plugins#114]
Hi,

I am using **audifileplayer** package to play a short mp3 audio clip from my app assets that is triggered at the end of the animation. When the app is on the foreground, it works, and the audio plays as expected. However, when the app is backgrounded, or the phone screen is off, it doesn't work - the audio is not triggered.

I did followed all the set up instructions for the background configurations for both Android and iOS. And I did ran flutter clean before restarting the app after I added the background config lines to the android manifest file.

Here's the function I am using on button press:

```
void _playAudioOnTimerEnd() {
    final _audioPlayer = Audio.load('assets/sounds/timerEnd.mp3', playInBackground: true);
    timerController.addListener(() {
      if ((timerController.duration.inSeconds - stopwatch.elapsed.inSeconds) ==
          4) {
        _audioPlayer..play()..dispose();
      }
    });
  }
```

When I send the app to the background the debug log prints the following message:
_I/AudiofileplayerPlugin(15319): LifecycleCallbacks.onActivityStopped_

And when I bring it back to the foreground, it prints the following log:
_I/AudiofileplayerPlugin(15319): LifecycleCallbacks.onActivityStarted
I/AudiofileplayerPlugin(15319): LifecycleCallbacks.onActivityResumed
I/AudiofileplayerService(15319): onGetRoot
I/AudiofileplayerPlugin(15319): ConnectionCallback.onConnected
I/AudiofileplayerPlugin(15319): LifecycleCallbacks.onActivityStopped_

Also, when the audio does trigger in the foreground mode, the phone shows a following notification from my app: "_'My App Name'_ is running Tap for more information or to stop the app." And before I restarted the app after running flutter clean it was showing the media notification instead, which would open the app, when tapped (but the background audio still did not play at that time).

I've spent three days already trying dozens of plugins but nothing works to play just a simple short audio effect when the app is backgrounded. I was hoping this package could solve it, but it didn't work for me either. Perhaps, it is not related to the plugin itself, but to the fact, that the Flutter code is not triggered on the background, but I don't know how to fix it.

I am running my app on real device Pixel 4a 5g.

Here's my flutter doctor output:

_$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

• No issues found!_

Really appreciate any help! Thanks!
Andrey

**Comment by monkeyswarm** [comment]
I modified the example app to see if I could recreate this behavior.

On main.dart, line 208, I replaced
```_backgroundAudio.resume()```
with
```Future.delayed(Duration(seconds:4), ()=> _backgroundAudio.resume());```
and commented out the rest of that method (which calls for system display of controls, which I assume you aren't using).

I tap 'play' on card 'Example 4'. Then close the app. After 4 seconds, the audio plays. This is on a Pixel 3a.

So I am not able to reproduce.

Looking at your code, I suspect your line 
```if ((timerController.duration.inSeconds - stopwatch.elapsed.inSeconds) ==  4)```
is to blame. Assuming that your timerController is firing on a regular basis, your audio would only play if the listener callback is fired at _exactly_ 4 seconds, which is very unlikely when comparing two floating point time representations. It's also possible that your timer controller or stopwatch do not increment while the app is backgrounded.

When you put a print statement before [audio.play], does it print?. Swap that callback and comparison logic with a [Future.delayed], like I did above, to confirm whether or not your [audio.play] call is actually called.

**Comment by asorokin** [comment]
Thanks a lot for looking into this! I don't even know how could I forget about Future.delayed... but it did work... of course. Yesterday, I even ended up using AlarmManager package to trigger the code in the background, which also solved my problem, but still didn't think about Future.delayed or Timer(), so silly.

Anyway, thank you again!
