### ISSUE TITLE
audiofileplayer is stopping background music when sound is played

### ISSUE THREAD

**Issue by peengle** [google/flutter.plugins#116]
I've noticed that when music is played in the background (eg Spotify) `Audio.load(audioFromAssets)..play()..dispose();` is stopping that music. 

Is there any way to play sound without stopping music that is already playing in the background?

**Comment by monkeyswarm** [comment]
I'm assuming this is on iOS? 
You want to set the audio session category via the 'setIosCategory' method: https://developer.apple.com/documentation/avfaudio/avaudiosessioncategory?language=objc
I believe the default is 'playback' which will not mix with other apps. You probably want 'ambient'.
