### ISSUE TITLE
Package not working.

### ISSUE THREAD

**Issue by PuneetDadhich** [google/flutter.plugins#119]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audioplayers:compileDebugKotlin'.
> Compilation error. See log for more details

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by monkeyswarm** [comment]
Please paste output of 'flutter doctor -v'

**Comment by PuneetDadhich** [comment]
![Screenshot 2021-08-24 222118](https://user-images.githubusercontent.com/63288532/130672014-6a49de40-18ba-4676-88fa-2fdffdfb9d10.png)

**Comment by monkeyswarm** [comment]
I dont' know anything about Kotlin, but it appears there is a mismatch, given the many errors:
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
If anyone knows where that expected 1.1.15 version is defined, I don't think it is defined anywhere in the audiofileplayers package.
Leaving open, but I suspect you have to change something in your project/editor preferences.
