### ISSUE TITLE
audiofileplayer - Support for lock screen controls

### ISSUE THREAD

**Issue by Sun3** [google/flutter.plugins#19]
I would like to suggest adding the feature to play audio in the background and especially showing play/pause, skip controls on the lock screen.

Thank you,

**Comment by monkeyswarm** [comment]
Try wrapping audiofileplayer in audio_service:
https://github.com/ryanheise/audio_service

**Comment by Sun3** [comment]
I have taken a look in the past at the audio_service plugin. I would love for the audiofileplayer plugin to be able to handle background audio and lock screen controls. Instead of using multiple audio plugins. It would make this a great plugin.

Thank you.

**Comment by monkeyswarm** [comment]
fixed by #35

**Comment by Sun3** [comment]
@monkeyswarm Thank you for adding the feature, its appreciated.
