### ISSUE TITLE
background in iOS work in simulator but not in my iPhone Pro Max

### ISSUE THREAD

**Issue by csacchetti** [google/flutter.plugins#26]
I tried the plugin with the example you made. Thank you for your work. It works fine. I've only found one problem for now: play in background with iOS. It works in simulator but not in release mode with the device  (I've an iPhone pro max with iOS 13.2.3).
Thanks
Carlo

**Comment by csacchetti** [comment]
Sorry. I try to download your example and it work also in my Device. But what's the difference to reproduce you example manually and download?

**Comment by monkeyswarm** [comment]
I'm not sure what you are asking: do you mean that the example app does work (does play in background), but you cannot get your own app code to do so? 

You have to set the static variable "shouldPlayWhileAppPaused" to "true" to get background audio. For iOS, the audio category also has to be set to "playback" (which should be the default as per release 1.0.2)

**Comment by csacchetti** [comment]
If I run your example application the plugin works. But when I replay the command
Checkbox(
              value: Audio.shouldPlayWhileAppPaused,
              onChanged: (bool isOn) =>
                  setState(() => Audio.shouldPlayWhileAppPaused = isOn)),
in my app It doesn't work. I add the plugin regularly 

import 'package:audiofileplayer/audiofileplayer.dart';

and I use the plugin for other function (I add instance of Audio: Audio _audio. But when I try to use Audio.shouldPlayWhileAppPaused my app doesn't play in background but stop it.
Can you help me.

**Comment by monkeyswarm** [comment]
Sounds like the iOS settings need to be updated.

Using Xcode, open your app's ios/Runner.xcodeproj, tap the "Runner" blueprint icon in the left-side explorer, tap "capabilities" tab across the top, go to "Background Modes" and enable the "Audio, Airplay, and Picture in Picture" mode.

Let me know if that works; if so, I should add some documentation for that.

Note that background audio does not work very well on Android at the moment (as it is associated with an Activity and will get killed after a few minutes in the background). I'd suggest wrapping audiofileplayer in the audio_service flutter plugin (which also adds lockscreen controls)

**Comment by csacchetti** [comment]
Ok, with this setting works. It's very good. 
How can I wrapping audiofileplayer in the audio_service flutter. Can you explain me the code. Thanks a lot.

**Comment by csacchetti** [comment]
I'd rather wait until your plugin problems are solved. Less plugin added is better. Plus, your plugin likes me for simplicity and philosophy. I'm joining who asked you to add the lock screen. With the solution to Android's problems and the lock screen would be a very great plugin. Thanks a lot for now.

**Comment by monkeyswarm** [comment]
Ok, I am working on full background audio support (including transport controls, etc), which will hopefully be published within the next several weeks.

**Comment by csacchetti** [comment]
Okay thanks a lot. I waiting for new developments. In the meantime I opened you a new issue in Android.
