### ISSUE TITLE
Error while invoking MediaControllerCompat$TransportControls

### ISSUE THREAD

**Issue by Andrewngabriel** [google/flutter.plugins#46]
First off, thanks for creating an awesome plugin which combines a lot of the pain points of other audio plugins and fixes them in one simple one.

I have migrated my project today to use this plugin but ran into an issue where I try to load a remote file stream but I get the following error message
```
I/flutter (32071): Attempt to invoke virtual method 'android.support.v4.media.session.MediaControllerCompat$TransportControls android.support.v4.media.session.MediaControllerCompat.getTransportControls()' on a null object reference
```
This error came from inside the `onError()` function which comes with `Audio.loadFromRemoteURL()` function.

I am not really sure what the issue could be. I made sure to add the `service` and `receiver` within `AndroidManifest.xml` file however nothing seems to fix it.

My project is open source and you can view where I am using the plugin here: https://github.com/Andrewngabriel/radio-player/blob/v0.1/lib/widgets/player.dart
Also, here is my AndroidManifest.xml file: https://github.com/Andrewngabriel/radio-player/blob/v0.1/android/app/src/main/AndroidManifest.xml

I would appreciate any help or pointers on this. Thanks 🙂

**Comment by monkeyswarm** [comment]
You are not using this audiofileplayer plugin. You are using the audio_service plugin. Please direct your questions there.

**Comment by rguntha** [comment]
I am facing the same issue. audio_service plug in is not working with audiofileplayer plugin. This issue is happening only in Android. It is working fine in IOS.
