### ISSUE TITLE
Future<List<Object>> function() {} doesn't show code suggestions for Flutter (Android Studio & Vscode)

### ISSUE THREAD

**Issue by babakoto** [google/flutter.plugins#85]
I have already tested:

-  **File/Invalidate cache** 
-  **remove ~/.dartServer/.analysis-driver/**

![image](https://user-images.githubusercontent.com/44688702/89742182-fdba8e00-da97-11ea-9a17-1d59f655b9ec.png)

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Users\babakoto\Downloads\flutter_windows_1.20.1-stable\flutter
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\babakoto\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\babakoto\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • MAR LX1A (mobile) • L2N0220319011997 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by monkeyswarm** [comment]
Flutter language/framework issues are tracked at the Flutter repository: https://github.com/flutter/flutter
