### ISSUE TITLE
The Small Icon is not loading for me sicne 1.3.3

### ISSUE THREAD

**Issue by arodriguezgb** [google/flutter.plugins#98]
@monkeyswarm 
Like the title says, the small icon shows as a blank square now. Code is still the same as before.

`  <meta-data android:name="ic_audiofileplayer" android:value="drawable/ic_gb_small_logo" />`

The icon is a transparent png, it used to work fine.

![Screen Shot 2021-02-07 at 1 49 18 PM](https://user-images.githubusercontent.com/53869855/107154813-4968ca00-694b-11eb-8f19-9dd082608979.png)

Could it be something with the asset loading fix that we need to change something ?

**Comment by monkeyswarm** [comment]
The asset loading changes in 1.3.3 are only for finding Flutter app assets in the /assets directory. It does not affect the Android system from finding content in the /res/drawable folders.

One other change in 1.3.3 is that the Android SDK version increased from 28 to 29. It's possible that Android introduced some change between those two SDK versions.

What Android OS version are you seeing this regression on?

**Comment by arodriguezgb** [comment]
10 and 11 on a Pixel 5, Galaxy S20 Ultra, and OnePlus 7 Pro

**Comment by arodriguezgb** [comment]
Same thing with this SDK 30 was making it not show up, switched back to 29 and its showing up now.

**Comment by arodriguezgb** [comment]
Closing

**Comment by arodriguezgb** [comment]
@monkeyswarm Same goes with the smallIcon, Sdk30.

**Comment by arodriguezgb** [comment]
@monkeyswarm Sorry to bother you again , but the issue not quite resolved on my end. The icon appears while debugging, but the release version on the play store does not show the icon. Any ideas?

**Comment by arodriguezgb** [comment]
@monkeyswarm Fixed on my end. 

If anyone has the issue I solved it by adding the same icon resouce to Drawable & Mipmap in all their respective sizes. 
 Edit: 
 I only had the icon on the Drawables folder.
