### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.media.session.MediaControllerCompat android.support.v4.media.session.MediaSessionCompat.getController()' on a null object reference

### ISSUE THREAD

**Issue by arodriguezgb** [google/flutter.plugins#99]
I am getting this on a Galaxy S20 Ultra

I start debugging on the phone and it crashes on startup. 
![Screen Shot 2021-02-10 at 12 06 30 AM](https://user-images.githubusercontent.com/53869855/107463179-f736cd00-6b33-11eb-90f8-026992af8b21.png)

**Comment by monkeyswarm** [comment]
- What version of Android
- Is this a regression (i.e. was it working earlier and it just broke on using 1.3.3)

**Comment by arodriguezgb** [comment]
Hey man I closed it, this was happening if the TargetSDKVersion of my app was 30, i switched back to 29 and it stoped happening.

**Comment by monkeyswarm** [comment]
ok, good to know that this will be an issue in the future whenever we update the SDK version
